export const modules = [
  {
    id: 'C00',
    name: 'C 00 - Basics & write()',
    exercises: ['ft_putchar', 'ft_print_alphabet', 'ft_print_reverse_alphabet', 'ft_print_numbers', 'ft_is_negative', 'ft_print_comb', 'ft_print_comb2', 'ft_putnbr', 'ft_print_combn'],
    problem: 'Write a function `void ft_print_combn(int n);` that displays all different combinations of n numbers by ascending order. n will be so that: 0 < n < 10.',
    quiz: [
      { q: 'What is the exact prototype for ft_putchar?', options: ['void ft_putchar(char c);', 'int ft_putchar(char c);', 'void ft_putchar(int c);', 'char ft_putchar(void);'], answer: 'void ft_putchar(char c);' },
      { q: 'According to the C00 subject, how must you call the write function?', options: ['write(1, c, 1);', 'write(1, &c, 1);', 'write(0, &c, 1);', 'write(&c, 1, 1);'], answer: 'write(1, &c, 1);' },
      { q: 'What does the first argument "1" in write(1, &c, 1) represent?', options: ['The number of bytes to write', 'Standard output (stdout)', 'Standard input (stdin)', 'Standard error (stderr)'], answer: 'Standard output (stdout)' },
      { q: 'What is the exact penalty for using a forbidden function?', options: ['0', '-1', '-42', 'Automatic expulsion'], answer: '-42' },
      { q: 'What compilation flags does Moulinette use?', options: ['-Wall -Werror', '-W -Wall -Werror', '-Wall -Wextra -Werror', '-Wall -Wextra'], answer: '-Wall -Wextra -Werror' },
      { q: 'What compiler does Moulinette use?', options: ['gcc', 'clang', 'cc', 'g++'], answer: 'cc' },
      { q: 'What happens if your program does not compile?', options: ['You get -1', 'You get 0', 'You get -42', 'You get a warning but it runs'], answer: 'You get 0' },
      { q: 'In ft_print_comb, why is 987 not in the expected output?', options: ['Because it is descending', 'Because 789 already is', 'Because it contains 9 twice', 'Because it is an odd number'], answer: 'Because 789 already is' },
      { q: 'In ft_print_comb, why is 999 not in the expected output?', options: ['Because 9 is present more than once', 'Because it is the last number', 'Because it is divisible by 3', 'Because 789 is already there'], answer: 'Because 9 is present more than once' },
      { q: 'What is the constraint for the parameter n in ft_print_combn?', options: ['0 <= n <= 10', '0 < n < 10', '1 < n < 9', 'n must be positive'], answer: '0 < n < 10' },
      { q: 'What must ft_putnbr be able to display?', options: ['Only positive numbers', 'All possible values within an int type variable', 'Only numbers up to 99', 'Only even numbers'], answer: 'All possible values within an int type variable' },
      { q: 'What is the minimum value of a 4-byte int?', options: ['-2147483648', '-32768', '0', '-2147483647'], answer: '-2147483648' },
      { q: 'What must you not forget to add in each of your .c/.h files?', options: ['A main function', 'The standard 42 header', 'A return statement', 'A comment block'], answer: 'The standard 42 header' },
      { q: 'What flag must Norminette be launched with in C00?', options: ['-R CheckForbiddenSourceHeader', '-R CheckDefine', '-R CheckGlobal', '-R CheckFunction'], answer: '-R CheckForbiddenSourceHeader' },
      { q: 'Will Moulinette evaluate a harder exercise if an easier one is not perfectly functional?', options: ['Yes, it averages the score', 'No, it will not take it into account', 'Only if the harder one passes Norminette', 'Only if you submit them in separate folders'], answer: 'No, it will not take it into account' },
      { q: 'In ft_is_negative, what is displayed if n is positive or null?', options: ['N', 'P', '0', '1'], answer: 'P' },
      { q: 'In ft_is_negative, what is displayed if n is negative?', options: ['N', 'P', '-1', '0'], answer: 'N' },
      { q: 'What is the output of ft_print_alphabet?', options: ['ZYXWVUTSRQPONMLKJIHGFEDCBA', 'abcdefghijklmnopqrstuvwxyz', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'aBcDeFgHiJkLmNoPqRsTuVwXyZ'], answer: 'abcdefghijklmnopqrstuvwxyz' },
      { q: 'What is the output of ft_print_reverse_alphabet?', options: ['ZYXWVUTSRQPONMLKJIHGFEDCBA', 'abcdefghijklmnopqrstuvwxyz', 'ZYXWVUTSRQPONMLKJIHGFEDCBA', 'zyxwvutsrqponmlkjihgfedcba'], answer: 'zyxwvutsrqponmlkjihgfedcba' },
      { q: 'What is the output of ft_print_numbers?', options: ['0123456789', '1234567890', '9876543210', '123456789'], answer: '0123456789' },
      { q: 'In ft_print_comb2, what is the last combination printed?', options: ['98 99', '99 99', '97 99', '99 98'], answer: '98 99' },
      { q: 'In ft_print_comb2, what is the first combination printed?', options: ['00 00', '00 01', '01 00', '00 00, 00 01'], answer: '00 01' },
      { q: 'What character separates the combinations in ft_print_comb2?', options: ['A space', 'A comma and a space', 'A newline', 'A semicolon'], answer: 'A comma and a space' },
      { q: 'What character separates the combinations in ft_print_comb?', options: ['A space', 'A comma and a space', 'A newline', 'A semicolon'], answer: 'A comma and a space' },
      { q: 'What should you do if you have a question according to C00 instructions?', options: ['Ask the staff immediately', 'Ask your peer on the right, then your peer on the left', 'Search the intranet only', 'Give up'], answer: 'Ask your peer on the right, then your peer on the left' },
    ]
  },
  {
    id: 'C01',
    name: 'C 01 - Pointers',
    exercises: ['ft_ft', 'ft_ultimate_ft', 'ft_swap', 'ft_div_mod', 'ft_ultimate_div_mod', 'ft_putstr', 'ft_strlen', 'ft_rev_int_tab', 'ft_sort_int_tab'],
    problem: 'Write a function `void ft_ultimate_div_mod(int *a, int *b);` that divides parameters a by b. The result is stored in the int pointed by a. The remainder is stored in the int pointed by b.',
    quiz: [
      { q: 'What value must ft_ft assign to the int?', options: ['0', '21', '42', '1337'], answer: '42' },
      { q: 'What is the prototype of ft_ultimate_ft?', options: ['void ft_ultimate_ft(int *********nbr);', 'void ft_ultimate_ft(int *******nbr);', 'void ft_ultimate_ft(int **nbr);', 'void ft_ultimate_ft(int nbr);'], answer: 'void ft_ultimate_ft(int *********nbr);' },
      { q: 'How many levels of pointers are in ft_ultimate_ft?', options: ['7', '8', '9', '10'], answer: '9' },
      { q: 'What is the prototype of ft_swap?', options: ['void ft_swap(int a, int b);', 'void ft_swap(int *a, int *b);', 'void ft_swap(int &a, int &b);', 'int ft_swap(int *a, int *b);'], answer: 'void ft_swap(int *a, int *b);' },
      { q: 'In ft_div_mod, where is the result of the division stored?', options: ['In the int pointed by div', 'In the int pointed by mod', 'It is returned', 'In a global variable'], answer: 'In the int pointed by div' },
      { q: 'In ft_div_mod, where is the remainder stored?', options: ['In the int pointed by div', 'In the int pointed by mod', 'It is returned', 'In a static variable'], answer: 'In the int pointed by mod' },
      { q: 'In ft_ultimate_div_mod, what happens to the remainder?', options: ['It is lost', 'It is stored in the int pointed by a', 'It is stored in the int pointed by b', 'It is printed'], answer: 'It is stored in the int pointed by b' },
      { q: 'In ft_ultimate_div_mod, what happens to the division result?', options: ['It is stored in the int pointed by a', 'It is stored in the int pointed by b', 'It is returned', 'It is discarded'], answer: 'It is stored in the int pointed by a' },
      { q: 'What function is allowed in C01 for ft_putstr?', options: ['printf', 'puts', 'write', 'putchar'], answer: 'write' },
      { q: 'What does ft_strlen return?', options: ['void', 'char *', 'int', 'unsigned int'], answer: 'int' },
      { q: 'What are the arguments for ft_rev_int_tab?', options: ['int *tab, int size', 'int *tab, int start, int end', 'int size, int *tab', 'char *tab, int size'], answer: 'int *tab, int size' },
      { q: 'How does ft_sort_int_tab sort the array?', options: ['By descending order', 'By ascending order', 'Alphabetically', 'Randomly'], answer: 'By ascending order' },
      { q: 'What happens if you divide by 0 in ft_div_mod?', options: ['Segmentation fault', 'Undefined behavior', 'Returns 0', 'Moulinette prevents it'], answer: 'Undefined behavior' },
      { q: 'What is the validation threshold for C01?', options: ['0%', '50%', '75%', '100%'], answer: '50%' },
      { q: 'To swap two integers without a temporary variable using XOR, what operator do you use?', options: ['&', '|', '^', '~'], answer: '^' },
      { q: 'What does the & operator do when applied to a variable (e.g., &a)?', options: ['Dereferences the pointer', 'Returns the memory address of the variable', 'Performs a bitwise AND', 'Returns the value of the variable'], answer: 'Returns the memory address of the variable' },
      { q: 'What does the * operator do when applied to a pointer (e.g., *a)?', options: ['Returns the memory address', 'Dereferences the pointer to get the value', 'Performs multiplication', 'Creates a new pointer'], answer: 'Dereferences the pointer to get the value' },
      { q: 'In ft_putstr, what is the condition to stop writing?', options: ['When *str is 0', 'When str is NULL', 'When size is reached', 'When a newline is found'], answer: 'When *str is 0' },
      { q: 'What is the complexity requirement for ft_sort_int_tab?', options: ['O(1)', 'O(n)', 'O(n log n)', 'No specific complexity required, just must work'], answer: 'No specific complexity required, just must work' },
      { q: 'Can you use standard library functions like <string.h> in C01?', options: ['Yes', 'No, only write is allowed', 'Only for testing', 'Only if you include them in the header'], answer: 'No, only write is allowed' },
    ]
  },
  {
    id: 'C02',
    name: 'C 02 - Strings',
    exercises: ['ft_strcpy', 'ft_strncpy', 'ft_str_is_alpha', 'ft_str_is_numeric', 'ft_str_is_lowercase', 'ft_str_is_uppercase', 'ft_str_is_printable', 'ft_strupcase', 'ft_strlowcase', 'ft_strcapitalize', 'ft_strlcpy', 'ft_putstr_non_printable', 'ft_print_memory'],
    problem: 'Write `void ft_putstr_non_printable(char *str);` that displays a string. If it contains non-printable characters, they must be displayed in the shape of hexadecimals (lowercase), preceded by a "backslash". Example: Coucou\\0atu vas bien ?',
    quiz: [
      { q: 'What does ft_strcpy return?', options: ['Nothing (void)', 'The destination string (dest)', 'The source string (src)', 'The length of the string'], answer: 'The destination string (dest)' },
      { q: 'What is the prototype of ft_strncpy?', options: ['char *ft_strncpy(char *dest, char *src);', 'char *ft_strncpy(char *dest, char *src, unsigned int n);', 'void ft_strncpy(char *dest, char *src, int n);', 'int ft_strncpy(char *dest, char *src, unsigned int n);'], answer: 'char *ft_strncpy(char *dest, char *src, unsigned int n);' },
      { q: 'What should ft_str_is_alpha return if the string is empty?', options: ['0', '1', 'NULL', '-1'], answer: '1' },
      { q: 'What should ft_str_is_numeric return for the string "42"?', options: ['0', '1', 'NULL', '4'], answer: '1' },
      { q: 'What is the ASCII range for lowercase letters?', options: ['65 to 90', '97 to 122', '48 to 57', '0 to 31'], answer: '97 to 122' },
      { q: 'What is the ASCII range for uppercase letters?', options: ['65 to 90', '97 to 122', '48 to 57', '32 to 126'], answer: '65 to 90' },
      { q: 'How is a "word" defined in ft_strcapitalize?', options: ['A string of only alphabetical characters', 'A string of alphanumeric characters', 'A string separated by spaces', 'Any sequence of non-printable chars'], answer: 'A string of alphanumeric characters' },
      { q: 'In ft_strcapitalize, what happens to the string "salut, comment tu vas ? 42mots quarante-deux; cinquante+et+un"?', options: ['Salut, Comment Tu Vas ? 42Mots Quarante-Deux; Cinquante+Et+Un', 'Salut, Comment Tu Vas ? 42mots Quarante-Deux; Cinquante+Et+Un', 'Salut, Comment Tu Vas ? 42mots quarante-deux; Cinquante+Et+Un', 'Salut, Comment Tu Vas ? 42mots Quarante-deux; Cinquante+Et+Un'], answer: 'Salut, Comment Tu Vas ? 42mots Quarante-Deux; Cinquante+Et+Un' },
      { q: 'What is the prototype of ft_strlcpy?', options: ['void ft_strlcpy(char *dest, char *src);', 'char *ft_strlcpy(char *dest, char *src, unsigned int n);', 'unsigned int ft_strlcpy(char *dest, char *src, unsigned int size);', 'int ft_strlcpy(char *dest, char *src);'], answer: 'unsigned int ft_strlcpy(char *dest, char *src, unsigned int size);' },
      { q: 'What does ft_strlcpy return?', options: ['The length of dest', 'The length of src', '0', 'The number of characters copied'], answer: 'The length of src' },
      { q: 'How does ft_putstr_non_printable display non-printable characters?', options: ['As octal values', 'As hexadecimal (lowercase) preceded by a backslash', 'As decimal values', 'Replaced by dots'], answer: 'As hexadecimal (lowercase) preceded by a backslash' },
      { q: 'In ft_print_memory, how many characters does each line handle?', options: ['8', '10', '16', '32'], answer: '16' },
      { q: 'In ft_print_memory, what replaces a non-printable character in the third column?', options: ['A space', 'A backslash', 'A dot (.)', 'A question mark (?)'], answer: 'A dot (.)' },
      { q: 'In ft_print_memory, what separates the hex address and the hex content?', options: ['A space', 'A colon and a space', 'A newline', 'A dash'], answer: 'A colon and a space' },
      { q: 'What is the ASCII value of the null terminator (\\0)?', options: ['0', '48', 'NULL', '\\n'], answer: '0' },
      { q: 'What is the ASCII range for printable characters (excluding space)?', options: ['32 to 126', '33 to 126', '65 to 122', '48 to 127'], answer: '33 to 126' },
      { q: 'Is space (\' \') considered printable by ft_str_is_printable?', options: ['Yes', 'No', 'Only if it is the first character', 'Only if it is the last character'], answer: 'Yes' },
      { q: 'What is the output of ft_strupcase("Hello World 42")?', options: ['Hello World 42', 'HELLO WORLD 42', 'hello world 42', 'Hello World 42'], answer: 'HELLO WORLD 42' },
      { q: 'What is the output of ft_strlowcase("Hello World 42")?', options: ['Hello World 42', 'HELLO WORLD 42', 'hello world 42', 'hELLO wORLD 42'], answer: 'hello world 42' },
      { q: 'In ft_print_memory, what is the first column?', options: ['The printable characters', 'The hex content of the memory', 'The hexadecimal address of the first character followed by a colon', 'The size of the memory block'], answer: 'The hexadecimal address of the first character followed by a colon' },
    ]
  },
  {
    id: 'C03',
    name: 'C 03 - String Manipulation',
    exercises: ['ft_strcmp', 'ft_strncmp', 'ft_strcat', 'ft_strncat', 'ft_strstr', 'ft_strlcat'],
    problem: 'Write `char *ft_strstr(char *str, char *to_find);` that reproduces the behavior of `strstr`. If `to_find` is an empty string, the function must return `str`.',
    quiz: [
      { q: 'What does ft_strcmp return?', options: ['A boolean (1 or 0)', 'The difference between the ASCII values of the first differing characters', 'The length of the strings', '0 if true, 1 if false'], answer: 'The difference between the ASCII values of the first differing characters' },
      { q: 'What is the third parameter of ft_strncmp?', options: ['char c', 'int n', 'unsigned int n', 'size_t n'], answer: 'unsigned int n' },
      { q: 'What does ft_strcat do?', options: ['Compares two strings', 'Concatenates src to dest', 'Finds the first occurrence of a substring', 'Copies a string'], answer: 'Concatenates src to dest' },
      { q: 'What is the prototype of ft_strncat?', options: ['char *ft_strncat(char *dest, char *src);', 'char *ft_strncat(char *dest, char *src, unsigned int nb);', 'void ft_strncat(char *dest, char *src, int nb);', 'int ft_strncat(char *dest, char *src);'], answer: 'char *ft_strncat(char *dest, char *src, unsigned int nb);' },
      { q: 'What does ft_strstr return if the substring is not found?', options: ['0', 'NULL', 'The original string', '-1'], answer: 'NULL' },
      { q: 'What does ft_strstr return if the substring is an empty string?', options: ['0', 'NULL', 'The original string', 'A segmentation fault occurs'], answer: 'The original string' },
      { q: 'What is the validation threshold for C03?', options: ['0%', '50%', '75%', '100%'], answer: '50%' },
      { q: 'What must ft_strlcat guarantee about the destination string?', options: ['It must be uppercase', 'It is always null-terminated (unless size is 0)', 'It must not contain spaces', 'It must be freed manually'], answer: 'It is always null-terminated (unless size is 0)' },
      { q: 'What does ft_strlcat return?', options: ['The length of dest', 'The total length of the string it tried to create (initial dest + src)', 'The number of characters appended', '0'], answer: 'The total length of the string it tried to create (initial dest + src)' },
      { q: 'What does ft_strcmp("abc", "abc") return?', options: ['1', '0', 'True', 'NULL'], answer: '0' },
      { q: 'What does ft_strcmp("a", "b") return?', options: ['1', '-1', '0', 'The difference between \'a\' and \'b\' (which is -1)'], answer: 'The difference between \'a\' and \'b\' (which is -1)' },
      { q: 'What does ft_strncmp("abc", "abd", 2) return?', options: ['1', '-1', '0', 'Error'], answer: '0' },
      { q: 'What does ft_strncmp("abc", "abd", 3) return?', options: ['1', '-1', '0', 'The difference between \'c\' and \'d\' (which is -1)'], answer: 'The difference between \'c\' and \'d\' (which is -1)' },
      { q: 'In ft_strcat, where does the src string get appended in dest?', options: ['At the very beginning of dest', 'Starting from the null terminator of dest', 'At the end of the allocated memory for dest', 'It overwrites dest from index 0'], answer: 'Starting from the null terminator of dest' },
      { q: 'What is the game mentioned in the C03 foreword?', options: ['Chess', 'Rock-paper-scissors', 'Go', 'Checkers'], answer: 'Rock-paper-scissors' },
      { q: 'What is the French name for Rock-paper-scissors mentioned in the PDF?', options: ['Shoushiling', 'Sansukumi-ken', 'Chi-fou-mi', 'Janken'], answer: 'Chi-fou-mi' },
      { q: 'In ft_strstr, if `to_find` is "world" and `str` is "Hello world", what is returned?', options: ['A pointer to the \'H\' in Hello', 'A pointer to the \'w\' in world', 'NULL', '0'], answer: 'A pointer to the \'w\' in world' },
      { q: 'What happens if dest does not have enough space for ft_strcat?', options: ['It reallocates dest', 'Undefined behavior (buffer overflow)', 'It returns NULL', 'It truncates src'], answer: 'Undefined behavior (buffer overflow)' },
      { q: 'What does the \'n\' in ft_strncat represent?', options: ['The maximum number of characters to append from src', 'The total size of dest', 'The number of times to append src', 'The index to start appending at'], answer: 'The maximum number of characters to append from src' },
      { q: 'If ft_strlcat is given a size of 0, what happens?', options: ['It appends 0 characters', 'It crashes', 'It returns the length of src', 'It returns 0'], answer: 'It returns the length of src' },
    ]
  },
  {
    id: 'C04',
    name: 'C 04 - Numbers & Bases',
    exercises: ['ft_strlen', 'ft_putstr', 'ft_putnbr', 'ft_atoi', 'ft_putnbr_base', 'ft_atoi_base'],
    problem: 'Write `int ft_atoi_base(char *str, char *base);` that converts the initial portion of `str` to an int representation, based on the given `base`. Handle whitespaces, signs, and invalid bases!',
    quiz: [
      { q: 'How does ft_atoi handle the string " ---+--+1234ab567"?', options: ['Returns 1234', 'Returns -1234', 'Returns 0', 'Returns 567'], answer: 'Returns -1234' },
      { q: 'What characters are considered whitespace by isspace(3)?', options: ['Only space', 'Space, tab, newline, carriage return, form feed, vertical tab', 'Space and tab', 'Any non-printable character'], answer: 'Space, tab, newline, carriage return, form feed, vertical tab' },
      { q: 'Which of the following makes a base INVALID for ft_putnbr_base?', options: ['Base contains +', 'Base contains -', 'Base contains duplicate characters', 'All of the above'], answer: 'All of the above' },
      { q: 'Must ft_putnbr_base handle negative numbers?', options: ['No', 'Yes', 'Only if the base is decimal', 'Only if the base is binary'], answer: 'Yes' },
      { q: 'What does ft_atoi_base return if the base is invalid?', options: ['0', '-1', 'NULL', 'The original string'], answer: '0' },
      { q: 'According to the subject, "poneyvif" is a base system for?', options: ['Decimal', 'Binary', 'Hexadecimal', 'Octal'], answer: 'Octal' },
      { q: 'What must ft_putnbr be able to display?', options: ['Only positive numbers', 'All possible values within an int type variable', 'Only numbers up to 99', 'Only even numbers'], answer: 'All possible values within an int type variable' },
      { q: 'How do you handle INT_MIN (-2147483648) in ft_putnbr?', options: ['Return 0', 'Cast to unsigned int or handle as a special case (long)', 'Print "-2147483648" manually', 'It is impossible'], answer: 'Cast to unsigned int or handle as a special case (long)' },
      { q: 'What is the base for "0123456789ABCDEF"?', options: ['Decimal', 'Binary', 'Hexadecimal', 'Octal'], answer: 'Hexadecimal' },
      { q: 'What is the base for "01"?', options: ['Decimal', 'Binary', 'Hexadecimal', 'Octal'], answer: 'Binary' },
      { q: 'What is the size of a valid base?', options: ['Exactly 10', 'Greater than 1', 'Greater than 0', 'Any size'], answer: 'Greater than 1' },
      { q: 'In ft_atoi, how is the sign of the returned number determined?', options: ['By the first character', 'By the number of \'-\' signs (odd or even)', 'By the number of \'+\' signs', 'It is always positive'], answer: 'By the number of \'-\' signs (odd or even)' },
      { q: 'In ft_atoi, what happens when a non-digit character is encountered?', options: ['It skips the character', 'It stops reading and returns the number found so far', 'It returns 0', 'It throws an error'], answer: 'It stops reading and returns the number found so far' },
      { q: 'Does ft_atoi handle overflow/underflow?', options: ['Yes, it returns NULL', 'Yes, it returns INT_MAX or INT_MIN', 'No, the result is undefined', 'Yes, it wraps around'], answer: 'No, the result is undefined' },
      { q: 'What is the prototype of ft_putnbr_base?', options: ['void ft_putnbr_base(int nbr, char *base);', 'int ft_putnbr_base(int nbr, char *base);', 'void ft_putnbr_base(char *nbr, char *base);', 'char *ft_putnbr_base(int nbr);'], answer: 'void ft_putnbr_base(int nbr, char *base);' },
      { q: 'What is the prototype of ft_atoi_base?', options: ['int ft_atoi_base(char *str, char *base);', 'void ft_atoi_base(char *str, char *base);', 'char *ft_atoi_base(int nbr, char *base);', 'int ft_atoi_base(char *str);'], answer: 'int ft_atoi_base(char *str, char *base);' },
      { q: 'If the base contains whitespace, what should ft_atoi_base do?', options: ['Ignore the whitespace', 'Return 0 (invalid base)', 'Treat it as a separator', 'Crash'], answer: 'Return 0 (invalid base)' },
      { q: 'What is the theme of the C04 foreword?', options: ['Harry Potter', 'Silicon Valley', 'City Hunter\'s "Moonlight Shadow"', 'The Big Lebowski'], answer: 'City Hunter\'s "Moonlight Shadow"' },
      { q: 'What does ft_putnbr_base do if the base is invalid?', options: ['Prints 0', 'Prints nothing', 'Prints the number in decimal', 'Prints "Error"'], answer: 'Prints nothing' },
      { q: 'In ft_putnbr_base, how do you convert a number to the base?', options: ['Divide by base length and keep remainders', 'Multiply by base length', 'Subtract base length repeatedly', 'Use printf'], answer: 'Divide by base length and keep remainders' },
    ]
  },
  {
    id: 'C05',
    name: 'C 05 - Math & Recursion',
    exercises: ['ft_iterative_factorial', 'ft_recursive_factorial', 'ft_iterative_power', 'ft_recursive_power', 'ft_fibonacci', 'ft_sqrt', 'ft_is_prime', 'ft_find_next_prime', 'ft_ten_queens_puzzle'],
    problem: 'Write `int ft_ten_queens_puzzle(void);` that displays all possible placements of ten queens on a chessboard. Recursivity is required. The return value must be the total number of displayed solutions.',
    quiz: [
      { q: 'What does ft_fibonacci return if the index is less than 0?', options: ['0', '1', '-1', 'NULL'], answer: '-1' },
      { q: 'What should ft_iterative_power return for 0 power 0?', options: ['0', '1', '-1', 'Undefined'], answer: '1' },
      { q: 'What does ft_sqrt return if the square root is an irrational number?', options: ['0', '-1', 'The integer part', 'NULL'], answer: '0' },
      { q: 'Are 0 and 1 considered prime numbers by ft_is_prime?', options: ['Yes', 'No', 'Only 1', 'Only 0'], answer: 'No' },
      { q: 'What does ft_find_next_prime return if the argument is already prime?', options: ['The next prime', 'The argument itself', '0', '-1'], answer: 'The argument itself' },
      { q: 'How is recursivity used in ft_ten_queens_puzzle?', options: ['It is optional', 'It is forbidden', 'It is required to solve the problem', 'Only for printing'], answer: 'It is required to solve the problem' },
      { q: 'In ft_ten_queens_puzzle, what does the first digit of the output represent?', options: ['The row of the Queen in the first column', 'The column of the Queen in the first row', 'The total number of Queens', 'The board size'], answer: 'The row of the Queen in the first column' },
      { q: 'What should ft_iterative_factorial return if the argument is not valid (e.g., negative)?', options: ['0', '-1', '1', 'The argument itself'], answer: '0' },
      { q: 'What is the starting sequence for ft_fibonacci?', options: ['1, 1, 2, 3', '0, 1, 1, 2', '1, 2, 3, 5', '0, 1, 2, 3'], answer: '0, 1, 1, 2' },
      { q: 'What is the maximum number of solutions for the Ten Queens puzzle?', options: ['100', '512', '724', '1024'], answer: '724' },
      { q: 'What is the prototype of ft_sqrt?', options: ['int ft_sqrt(int nb);', 'double ft_sqrt(int nb);', 'void ft_sqrt(int nb);', 'int ft_sqrt(unsigned int nb);'], answer: 'int ft_sqrt(int nb);' },
      { q: 'What is the prototype of ft_is_prime?', options: ['int ft_is_prime(int nb);', 'void ft_is_prime(int nb);', 'char ft_is_prime(int nb);', 'int ft_is_prime(unsigned int nb);'], answer: 'int ft_is_prime(int nb);' },
      { q: 'What is a simple optimization for ft_is_prime?', options: ['Check divisibility up to nb', 'Check divisibility up to nb/2', 'Check divisibility up to sqrt(nb)', 'Check divisibility by 2 and 3 only'], answer: 'Check divisibility up to sqrt(nb)' },
      { q: 'What should ft_recursive_factorial return for a negative input?', options: ['0', '-1', 'Crash', '1'], answer: '0' },
      { q: 'What should ft_recursive_power return for a power lower than 0?', options: ['0', '-1', '1', 'Undefined'], answer: '0' },
      { q: 'Does ft_fibonacci need to handle overflows?', options: ['Yes, return -1', 'Yes, return INT_MAX', 'No, the return is undefined', 'Yes, wrap around'], answer: 'No, the return is undefined' },
      { q: 'In ft_ten_queens_puzzle, how are the solutions displayed?', options: ['One per line, as 10 digits', 'As a grid of Qs and .s', 'Separated by commas', 'In a single line'], answer: 'One per line, as 10 digits' },
      { q: 'What is the theme of the C05 foreword?', options: ['Harry Potter Sorting Hat', 'Silicon Valley', 'The Big Lebowski', 'Rick and Morty'], answer: 'Harry Potter Sorting Hat' },
      { q: 'What must ft_ten_queens_puzzle return?', options: ['void', 'The total number of displayed solutions', 'The first solution', '0 on success'], answer: 'The total number of displayed solutions' },
      { q: 'What is the 0th element of the Fibonacci sequence?', options: ['1', '0', '-1', 'NULL'], answer: '0' },
    ]
  },
  {
    id: 'C06',
    name: 'C 06 - Command Line Arguments',
    exercises: ['ft_print_program_name', 'ft_print_params', 'ft_rev_params', 'ft_sort_params'],
    problem: 'Write a program `ft_sort_params.c` that displays its given arguments sorted by ASCII order. It should display all arguments, except for argv[0]. One argument per line.',
    quiz: [
      { q: 'Do you need to submit a main() function for C06?', options: ['No, only libraries', 'Yes, because they are programs', 'Only for ex00', 'Only if requested by Moulinette'], answer: 'Yes, because they are programs' },
      { q: 'What does ft_print_program_name display?', options: ['The first argument passed to the program', 'The name of the user', 'The current directory', 'Nothing'], answer: 'The first argument passed to the program' },
      { q: 'In ft_print_params, which arguments should be displayed?', options: ['All arguments', 'All arguments except argv[0]', 'Only argv[0]', 'Only the first 3 arguments'], answer: 'All arguments except argv[0]' },
      { q: 'What is the output order of ft_rev_params?', options: ['Ascending order', 'Descending order', 'Reverse order of the command line', 'Random order'], answer: 'Reverse order of the command line' },
      { q: 'How does ft_sort_params sort the arguments?', options: ['By length', 'By ASCII order', 'Alphabetically ignoring case', 'Reverse alphabetical'], answer: 'By ASCII order' },
      { q: 'How many arguments per line are displayed in ft_sort_params?', options: ['One', 'Two', 'Five', 'All on one line'], answer: 'One' },
      { q: 'What is the index of the program name in argv?', options: ['1', '0', '-1', 'argc'], answer: '0' },
      { q: 'What does argc represent?', options: ['The total number of characters in argv', 'The number of arguments passed to the program', 'The index of the last argument', 'The memory address of argv'], answer: 'The number of arguments passed to the program' },
      { q: 'What is the type of argv?', options: ['char *', 'char **', 'int *', 'char ***'], answer: 'char **' },
      { q: 'If you run `./a.out test1 test2`, what is argv[0]?', options: ['test1', 'test2', './a.out', 'NULL'], answer: './a.out' },
      { q: 'If you run `./a.out test1 test2`, what is argv[1]?', options: ['test1', 'test2', './a.out', 'NULL'], answer: 'test1' },
      { q: 'If you run `./a.out test1 test2`, what is argc?', options: ['1', '2', '3', '0'], answer: '3' },
      { q: 'What is the last element of argv?', options: ['The last argument', 'argc', 'NULL', '0'], answer: 'NULL' },
      { q: 'What function is allowed in C06?', options: ['printf', 'write', 'malloc', 'puts'], answer: 'write' },
      { q: 'In ft_sort_params, what happens if two strings are identical?', options: ['They are both displayed in their original order', 'One is discarded', 'They are sorted randomly', 'It crashes'], answer: 'They are both displayed in their original order' },
      { q: 'What is the theme of the C06 foreword?', options: ['The Big Lebowski', 'Harry Potter', 'Silicon Valley', 'City Hunter'], answer: 'The Big Lebowski' },
      { q: 'In the Big Lebowski foreword, what score does Walter demand Smokey mark?', options: ['8', '0', '7', '-42'], answer: '0' },
      { q: 'How do you compare two strings in C to sort them in ft_sort_params?', options: ['Using ==', 'Using strcmp or ft_strcmp', 'Using >', 'Using diff'], answer: 'Using strcmp or ft_strcmp' },
      { q: 'How do you swap two strings in an array of strings (char **)?', options: ['Swap the characters one by one', 'Swap the pointers', 'Use strcpy', 'You cannot swap strings'], answer: 'Swap the pointers' },
      { q: 'What is the return type of main in C06?', options: ['void', 'int', 'char', 'float'], answer: 'int' },
    ]
  },
  {
    id: 'C07',
    name: 'C 07 - Memory Allocation (malloc)',
    exercises: ['ft_strdup', 'ft_range', 'ft_ultimate_range', 'ft_strjoin', 'ft_convert_base', 'ft_split'],
    problem: 'Write `char **ft_split(char *str, char *charset);` that splits a string depending on the charset. The function returns an array of strings. The last element must equal 0. There cannot be any empty strings in the array.',
    quiz: [
      { q: 'Which function is newly allowed in C07?', options: ['printf', 'malloc', 'free', 'read'], answer: 'malloc' },
      { q: 'What should ft_range return if min >= max?', options: ['0', 'NULL', 'A negative number', 'An empty array'], answer: 'NULL' },
      { q: 'What does ft_ultimate_range return on success?', options: ['The array of ints', 'The size of the range', '0', 'NULL'], answer: 'The size of the range' },
      { q: 'What must ft_strjoin return if `size` is 0?', options: ['NULL', '0', 'An empty string that can be freed', 'A pointer to the separator'], answer: 'An empty string that can be freed' },
      { q: 'What happens to the returned number in ft_convert_base if it is negative?', options: ['It has no sign', 'It is prefixed by a single and unique \'-\'', 'It is prefixed by multiple \'-\'', 'It is returned as positive'], answer: 'It is prefixed by a single and unique \'-\'' },
      { q: 'What marks the end of the array returned by ft_split?', options: ['A NULL character (0)', 'A newline', 'The size of the array', 'An empty string'], answer: 'A NULL character (0)' },
      { q: 'Can there be empty strings in the array returned by ft_split?', options: ['Yes', 'No', 'Only at the beginning', 'Only at the end'], answer: 'No' },
      { q: 'What does ft_strdup do?', options: ['Compares two strings', 'Duplicates a string by allocating memory', 'Splits a string', 'Reverses a string'], answer: 'Duplicates a string by allocating memory' },
      { q: 'What is the prototype of ft_strdup?', options: ['char *ft_strdup(char *src);', 'void ft_strdup(char *src);', 'char *ft_strdup(char *dest, char *src);', 'int ft_strdup(char *src);'], answer: 'char *ft_strdup(char *src);' },
      { q: 'What is the prototype of ft_range?', options: ['int *ft_range(int min, int max);', 'int ft_range(int min, int max);', 'void ft_range(int *range, int min, int max);', 'int *ft_range(int min, int max, int size);'], answer: 'int *ft_range(int min, int max);' },
      { q: 'What is the prototype of ft_ultimate_range?', options: ['int *ft_ultimate_range(int min, int max);', 'int ft_ultimate_range(int **range, int min, int max);', 'void ft_ultimate_range(int *range, int min, int max);', 'int **ft_ultimate_range(int min, int max);'], answer: 'int ft_ultimate_range(int **range, int min, int max);' },
      { q: 'What is the prototype of ft_strjoin?', options: ['char *ft_strjoin(char **strs, char *sep);', 'char *ft_strjoin(int size, char **strs, char *sep);', 'char *ft_strjoin(char *s1, char *s2);', 'void ft_strjoin(int size, char **strs);'], answer: 'char *ft_strjoin(int size, char **strs, char *sep);' },
      { q: 'What must ft_ultimate_range return on error (e.g., malloc fails)?', options: ['0', '-1', 'NULL', 'The range pointer'], answer: '-1' },
      { q: 'What happens if min equals max in ft_ultimate_range?', options: ['Returns -1', 'Range points to NULL and returns 0', 'Returns 1', 'Crashes'], answer: 'Range points to NULL and returns 0' },
      { q: 'In ft_split, can the string given as argument be modified?', options: ['Yes', 'No', 'Only if it is a const char*', 'Only the separators can be modified'], answer: 'No' },
      { q: 'What is the theme of the C07 foreword?', options: ['Rick and Morty', 'The Big Lebowski', 'Harry Potter', 'Silicon Valley'], answer: 'Rick and Morty' },
      { q: 'In the Rick and Morty foreword, what fuel did Rick invent?', options: ['Plutonium', 'Concentrated dark matter', 'Flux Capacitor', 'Unobtainium'], answer: 'Concentrated dark matter' },
      { q: 'What does ft_convert_base return if a base is wrong?', options: ['0', 'NULL', '-1', 'The original number'], answer: 'NULL' },
      { q: 'What functions are allowed in ft_convert_base?', options: ['malloc, free', 'write, malloc', 'Only malloc', 'malloc, free, write'], answer: 'malloc, free' },
      { q: 'In ft_strjoin, what is the `size` parameter?', options: ['The total length of the final string', 'The number of strings in strs', 'The size of the separator', 'The memory to allocate'], answer: 'The number of strings in strs' },
    ]
  },
  {
    id: 'C08',
    name: 'C 08 - Headers & Structs',
    exercises: ['ft.h', 'ft_boolean.h', 'ft_abs.h', 'ft_point.h', 'ft_strs_to_tab', 'ft_show_tab'],
    problem: 'Create `ft_abs.h` that defines a macro `ABS` which replaces its argument by its absolute value. Then write `struct s_stock_str *ft_strs_to_tab(int ac, char **av);` which transforms `av` into a structure array containing size, str, and copy.',
    quiz: [
      { q: 'What type of file are you required to create in ex00 of C08?', options: ['.c source file', '.h header file', 'Makefile', 'Shell script'], answer: '.h header file' },
      { q: 'What does the ft_boolean.h file define?', options: ['Variables', 'Macros like TRUE, FALSE, EVEN, ODD', 'Structures', 'Main functions'], answer: 'Macros like TRUE, FALSE, EVEN, ODD' },
      { q: 'What flag must Norminette be launched with for C08?', options: ['-R CheckForbiddenSourceHeader', '-R CheckDefine', '-R CheckGlobal', '-R CheckFunction'], answer: '-R CheckDefine' },
      { q: 'What is the prototype of `ft_strs_to_tab`?', options: ['char *ft_strs_to_tab(int ac, char **av);', 'struct s_stock_str *ft_strs_to_tab(int ac, char **av);', 'int ft_strs_to_tab(char **av);', 'void ft_strs_to_tab(t_stock_str *str);'], answer: 'struct s_stock_str *ft_strs_to_tab(int ac, char **av);' },
      { q: 'What must the last element\'s `str` be set to in `ft_strs_to_tab`?', options: ['0', 'NULL', '-1', '""'], answer: '0' },
      { q: 'In ft_show_tab, what is displayed for each element?', options: ['Only the string', 'The string, size, and copy, each followed by a newline', 'The size and copy', 'The copy and size'], answer: 'The string, size, and copy, each followed by a newline' },
      { q: 'What is the structure defined in ft_stock_str.h?', options: ['struct s_stock_str { int size; char *str; char *copy; }', 'struct s_stock_str { char *str; int size; char *copy; }', 'struct s_stock { int size; char *str; }', 'typedef struct s_str { int size; char *str; }'], answer: 'struct s_stock_str { int size; char *str; char *copy; }' },
      { q: 'What is the name of the typedef for the structure in C08?', options: ['t_str', 't_stock', 't_stock_str', 's_stock_str'], answer: 't_stock_str' },
      { q: 'What does the ABS macro do in ft_abs.h?', options: ['Returns the absolute value of a number', 'Returns the negative value of a number', 'Checks if a number is positive', 'Adds two numbers'], answer: 'Returns the absolute value of a number' },
      { q: 'How is a macro defined in C?', options: ['#define MACRO(value)', '#macro MACRO(value)', '#def MACRO(value)', 'define MACRO(value)'], answer: '#define MACRO(value)' },
      { q: 'What is the structure of the t_point struct in ft_point.h?', options: ['struct s_point { int x; int y; }', 'struct s_point { float x; float y; }', 'struct s_point { int x; char y; }', 'struct point { int x; int y; }'], answer: 'struct s_point { int x; int y; }' },
      { q: 'What is the typedef for the point struct?', options: ['t_pt', 't_point', 't_pos', 'point_t'], answer: 't_point' },
      { q: 'What should `ft_strs_to_tab` return if an error occurs (e.g., malloc fails)?', options: ['0', 'NULL', '-1', 'The last valid element'], answer: 'NULL' },
      { q: 'What functions are allowed in `ft_strs_to_tab`?', options: ['malloc, free', 'write, malloc', 'Only malloc', 'malloc, free, write'], answer: 'malloc, free' },
      { q: 'What function is allowed in `ft_show_tab`?', options: ['printf', 'write', 'putchar', 'malloc'], answer: 'write' },
      { q: 'What is the theme of the C08 foreword?', options: ['Platypus', 'Rick and Morty', 'The Big Lebowski', 'Harry Potter'], answer: 'Platypus' },
      { q: 'In ft_boolean.h, what does the EVEN macro do?', options: ['Returns 1 if odd, 0 if even', 'Returns 1 if even, 0 if odd', 'Returns the number divided by 2', 'Returns TRUE if even, FALSE if odd'], answer: 'Returns 1 if even, 0 if odd' },
      { q: 'In the ft_boolean.h main test, what message is printed for an even number of arguments?', options: ['I have an even number of arguments.', 'Even args.', 'Args are even.', 'EVEN_MSG'], answer: 'I have an even number of arguments.' },
      { q: 'What is the return value of main in the ft_boolean.h test?', options: ['0', '1', 'SUCCESS', 'EXIT_SUCCESS'], answer: 'SUCCESS' },
      { q: 'Why do we use header guards (#ifndef) in .h files?', options: ['To prevent multiple inclusions of the same header', 'To speed up compilation', 'To hide code from Moulinette', 'To define macros'], answer: 'To prevent multiple inclusions of the same header' },
    ]
  },
  {
    id: 'C09',
    name: 'C 09 - Makefiles & libft',
    exercises: ['libft', 'Makefile', 'ft_split'],
    problem: 'Write a `Makefile` that compiles a library `libft.a`. It must get its source files from the `srcs` directory and headers from `includes`. Implement `all`, `clean`, `fclean`, and `re`. The Makefile should print all the commands it\'s running.',
    quiz: [
      { q: 'What script must you create to compile your library in ex00?', options: ['compile.sh', 'libft_creator.sh', 'run.sh', 'build.sh'], answer: 'libft_creator.sh' },
      { q: 'What is the name of the library you must create?', options: ['lib42.a', 'libft.so', 'libft.a', 'mylib.a'], answer: 'libft.a' },
      { q: 'What rules must the Makefile in C09 implement?', options: ['all, clean, fclean, re, libft.a', 'build, run, stop', 'compile, link, execute', 'start, end'], answer: 'all, clean, fclean, re, libft.a' },
      { q: 'What flags must be used when compiling with cc in C09?', options: ['-Wall -Wextra -Werror', '-W -Werror -Wall', '-Wall -We -Werr', '-g -Wall'], answer: '-Wall -Wextra -Werror' },
      { q: 'Where should the .o files be placed?', options: ['In a separate obj/ directory', 'Near their .c file', 'In the root directory', 'They shouldn\'t exist'], answer: 'Near their .c file' },
      { q: 'Where does the Makefile get its source files from?', options: ['The root directory', 'The "srcs" directory', 'The "includes" directory', 'The "obj" directory'], answer: 'The "srcs" directory' },
      { q: 'What should `make` be equal to by default?', options: ['make clean', 'make all', 'make fclean', 'make re'], answer: 'make all' },
      { q: 'What should `make all` be equal to?', options: ['make libft.a', 'make compile', 'make build', 'make srcs'], answer: 'make libft.a' },
      { q: 'What does `make clean` do?', options: ['Removes the executable', 'Removes all temporary generated files (like .o)', 'Removes everything', 'Recompiles everything'], answer: 'Removes all temporary generated files (like .o)' },
      { q: 'What does `make fclean` do?', options: ['Just removes .o files', 'Does a make clean plus removes the binary/library', 'Formats the drive', 'Fixes formatting errors'], answer: 'Does a make clean plus removes the binary/library' },
      { q: 'What does `make re` do?', options: ['Reboots the system', 'Does a make fclean followed by make all', 'Recompiles only changed files', 'Runs Norminette'], answer: 'Does a make fclean followed by make all' },
      { q: 'Where does the Makefile get its header files from?', options: ['The "srcs" directory', 'The "includes" directory', 'The root directory', 'The system path'], answer: 'The "includes" directory' },
      { q: 'What command creates a static library from .o files?', options: ['gcc -c', 'ar rcs', 'ld -o', 'make lib'], answer: 'ar rcs' },
      { q: 'What does the `-Wall` flag do?', options: ['Enables all warnings', 'Enables extra warnings', 'Treats warnings as errors', 'Optimizes the code'], answer: 'Enables all warnings' },
      { q: 'What does the `-Wextra` flag do?', options: ['Enables all warnings', 'Enables extra warnings', 'Treats warnings as errors', 'Disables warnings'], answer: 'Enables extra warnings' },
      { q: 'What does the `-Werror` flag do?', options: ['Enables all warnings', 'Enables extra warnings', 'Treats warnings as errors', 'Adds debug info'], answer: 'Treats warnings as errors' },
      { q: 'What is the theme of the C09 foreword?', options: ['The Big Lebowski', 'Rick and Morty', 'Harry Potter', 'Platypus'], answer: 'The Big Lebowski' },
      { q: 'What does the shell script `libft_creator.sh` do?', options: ['Runs Norminette', 'Compiles source files and creates the library', 'Pushes to Git', 'Creates the srcs directory'], answer: 'Compiles source files and creates the library' },
      { q: 'How do you run the shell script?', options: ['./libft_creator.sh', 'sh libft_creator.sh', 'run libft_creator.sh', 'exec libft_creator.sh'], answer: 'sh libft_creator.sh' },
      { q: 'What must you watch out for in your Makefile according to the PDF?', options: ['Wildcards', 'Memory leaks', 'Syntax errors', 'Long compilation times'], answer: 'Wildcards' },
      { q: 'What does the `ar` command stand for?', options: ['Archive', 'Array', 'Argument', 'Arc'], answer: 'Archive' },
      { q: 'What does the `rcs` in `ar rcs` stand for?', options: ['Run, Compile, Save', 'Replace, Create, Symbol', 'Read, Create, Static', 'Recompile, Clean, Source'], answer: 'Replace, Create, Symbol' },
      { q: 'Can a Makefile run unnecessary commands?', options: ['Yes, it doesn\'t matter', 'No, it should not run any unnecessary command', 'Only during `make re`', 'Only if using wildcards'], answer: 'No, it should not run any unnecessary command' },
      { q: 'What is the prototype of ft_split in C09?', options: ['char *ft_split(char *str, char *charset);', 'char **ft_split(char *str, char *charset);', 'char **ft_split(char **str, char *charset);', 'void ft_split(char *str);'], answer: 'char **ft_split(char *str, char *charset);' },
      { q: 'What functions are allowed for ft_split in C09?', options: ['write', 'malloc', 'malloc and free', 'printf'], answer: 'malloc' },
    ]
  }
];
